name: C/C++ Build and Test

on: [push]

jobs:
  build_and_test_ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ls -la && gcc --version
    - name: build
      run: ls -la && cd advent2019_1a && g++ main.cpp 
    - name: run test
      run: cd advent2019_1a && ./a.out
