name: C/C++ Build and Test

on: [push]

jobs:
  build_and_test_gcc_ubuntu:

    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
    - uses: actions/checkout@v1
    - name: print configure
      run: |
        ls -la
        uname -a
        gcc --version 
    - name: build
      run: |
        cd advent2019_1a
        g++ main.cpp 
    - name: run test
      run: |
        cd advent2019_1a
        ./a.out

  build_and_test_clang_ubuntu:

    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ls -la && uname -a && clang --version

  build_and_test_gcc_mac:

    runs-on: macos-latest
    timeout-minutes: 3
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ls -la && uname -a && gcc --version
    - name: build
      run: cd advent2019_1a && g++ main.cpp 
    - name: run test
      run: cd advent2019_1a && ./a.out