name: C/C++ CI

on: [push]

jobs:
  build_and_test_gcc_ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
    - uses: actions/checkout@v1
    - name: print environment
      run: |
        ls -la
        uname -a
        gcc --version 
    - name: build
      run: |
        cd advent2019_1a
        g++ -std=c++17 -Wall -pedantic main.cpp 
        cd ..
        cd advent2019_1b
        g++ -std=c++17 -Wall -pedantic main.cpp
    - name: run test
      run: |
        ./advent2019_1a/a.out
        ./advent2019_1b/a.out

  build_and_test_clang:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    timeout-minutes: 3
    
    steps:
    - uses: actions/checkout@v1
    - name: print environment
      run: |
        pwd
        ls -la
        echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
        ls -la $GITHUB_WORKSPACE
        uname -a
        clang --version
    - name: build
      run: |
        cd advent2019_1a
        clang++ -std=c++17 -Wall -pedantic main.cpp
        cd ..
        cd advent2019_1b
        clang++ -std=c++17 -Wall -pedantic main.cpp
    - name: run test
      run: |
        cd $GITHUB_WORKSPACE/advent2019_1a && ./a.out
        cd $GITHUB_WORKSPACE/advent2019_1b && ./a.out